server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: second-service
          uri: lb://second-service
          predicates:
            - Path=/second-service/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true